package com.collagehelper.dataobject;

public class APDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_person.id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_person.assemble_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String assembleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_person.phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_person.status
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_person.id
     *
     * @return the value of assemble_person.id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_person.id
     *
     * @param id the value for assemble_person.id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_person.assemble_id
     *
     * @return the value of assemble_person.assemble_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getAssembleId() {
        return assembleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_person.assemble_id
     *
     * @param assembleId the value for assemble_person.assemble_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setAssembleId(String assembleId) {
        this.assembleId = assembleId == null ? null : assembleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_person.phone
     *
     * @return the value of assemble_person.phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_person.phone
     *
     * @param phone the value for assemble_person.phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_person.status
     *
     * @return the value of assemble_person.status
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_person.status
     *
     * @param status the value for assemble_person.status
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}