package com.collagehelper.dataobject;

public class AssembleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.customer_phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String customerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.seller_phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String sellerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.assemble_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String assembleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.time
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.money
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.goods_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.goods_count
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_info.status
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.id
     *
     * @return the value of assemble_info.id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.id
     *
     * @param id the value for assemble_info.id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.customer_phone
     *
     * @return the value of assemble_info.customer_phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.customer_phone
     *
     * @param customerPhone the value for assemble_info.customer_phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.seller_phone
     *
     * @return the value of assemble_info.seller_phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getSellerPhone() {
        return sellerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.seller_phone
     *
     * @param sellerPhone the value for assemble_info.seller_phone
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setSellerPhone(String sellerPhone) {
        this.sellerPhone = sellerPhone == null ? null : sellerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.assemble_id
     *
     * @return the value of assemble_info.assemble_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getAssembleId() {
        return assembleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.assemble_id
     *
     * @param assembleId the value for assemble_info.assemble_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setAssembleId(String assembleId) {
        this.assembleId = assembleId == null ? null : assembleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.time
     *
     * @return the value of assemble_info.time
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.time
     *
     * @param time the value for assemble_info.time
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.money
     *
     * @return the value of assemble_info.money
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.money
     *
     * @param money the value for assemble_info.money
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.goods_id
     *
     * @return the value of assemble_info.goods_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.goods_id
     *
     * @param goodsId the value for assemble_info.goods_id
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.goods_count
     *
     * @return the value of assemble_info.goods_count
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.goods_count
     *
     * @param goodsCount the value for assemble_info.goods_count
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_info.status
     *
     * @return the value of assemble_info.status
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_info.status
     *
     * @param status the value for assemble_info.status
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}