package com.collagehelper.dataobject;

public class CartDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.id
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.phone
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.goods_id
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.goods_count
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    private Integer goodsCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.id
     *
     * @return the value of cart_info.id
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.id
     *
     * @param id the value for cart_info.id
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.phone
     *
     * @return the value of cart_info.phone
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.phone
     *
     * @param phone the value for cart_info.phone
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.goods_id
     *
     * @return the value of cart_info.goods_id
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.goods_id
     *
     * @param goodsId the value for cart_info.goods_id
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.goods_count
     *
     * @return the value of cart_info.goods_count
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.goods_count
     *
     * @param goodsCount the value for cart_info.goods_count
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }
}