package com.collagehelper.dataobject;

public class CGDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_goods.id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_goods.phone
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_goods.goods_id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_goods.id
     *
     * @return the value of collect_goods.id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_goods.id
     *
     * @param id the value for collect_goods.id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_goods.phone
     *
     * @return the value of collect_goods.phone
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_goods.phone
     *
     * @param phone the value for collect_goods.phone
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_goods.goods_id
     *
     * @return the value of collect_goods.goods_id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_goods.goods_id
     *
     * @param goodsId the value for collect_goods.goods_id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}