package com.collagehelper.dataobject;

public class COCDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_on_comment.id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_on_comment.comment_id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_on_comment.comment
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_on_comment.time
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_on_comment.phone
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_on_comment.id
     *
     * @return the value of comment_on_comment.id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_on_comment.id
     *
     * @param id the value for comment_on_comment.id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_on_comment.comment_id
     *
     * @return the value of comment_on_comment.comment_id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_on_comment.comment_id
     *
     * @param commentId the value for comment_on_comment.comment_id
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_on_comment.comment
     *
     * @return the value of comment_on_comment.comment
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_on_comment.comment
     *
     * @param comment the value for comment_on_comment.comment
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_on_comment.time
     *
     * @return the value of comment_on_comment.time
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_on_comment.time
     *
     * @param time the value for comment_on_comment.time
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_on_comment.phone
     *
     * @return the value of comment_on_comment.phone
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_on_comment.phone
     *
     * @param phone the value for comment_on_comment.phone
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}