package com.collagehelper.dataobject;

public class CTSDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_to_seller.id
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_to_seller.customer_phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private String customerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_to_seller.seller_phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private String sellerPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_to_seller.id
     *
     * @return the value of customer_to_seller.id
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_to_seller.id
     *
     * @param id the value for customer_to_seller.id
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_to_seller.customer_phone
     *
     * @return the value of customer_to_seller.customer_phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_to_seller.customer_phone
     *
     * @param customerPhone the value for customer_to_seller.customer_phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_to_seller.seller_phone
     *
     * @return the value of customer_to_seller.seller_phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public String getSellerPhone() {
        return sellerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_to_seller.seller_phone
     *
     * @param sellerPhone the value for customer_to_seller.seller_phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setSellerPhone(String sellerPhone) {
        this.sellerPhone = sellerPhone == null ? null : sellerPhone.trim();
    }
}