package com.collagehelper.dataobject;

public class GoodsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_id
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_img
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_name
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_price
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private String goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_des
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    private String goodsDes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_id
     *
     * @return the value of goods_info.goods_id
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_id
     *
     * @param goodsId the value for goods_info.goods_id
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.phone
     *
     * @return the value of goods_info.phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.phone
     *
     * @param phone the value for goods_info.phone
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_img
     *
     * @return the value of goods_info.goods_img
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_img
     *
     * @param goodsImg the value for goods_info.goods_img
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_name
     *
     * @return the value of goods_info.goods_name
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_name
     *
     * @param goodsName the value for goods_info.goods_name
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_price
     *
     * @return the value of goods_info.goods_price
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public String getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_price
     *
     * @param goodsPrice the value for goods_info.goods_price
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice == null ? null : goodsPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_des
     *
     * @return the value of goods_info.goods_des
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public String getGoodsDes() {
        return goodsDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_des
     *
     * @param goodsDes the value for goods_info.goods_des
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    public void setGoodsDes(String goodsDes) {
        this.goodsDes = goodsDes == null ? null : goodsDes.trim();
    }
}