package com.collagehelper.dao;

import com.collagehelper.dataobject.AssembleDO;

import java.util.List;

public interface AssembleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_info
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_info
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    int insert(AssembleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_info
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    int insertSelective(AssembleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_info
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    AssembleDO selectByPrimaryKey(Integer id);

    List<AssembleDO> selectAll();

    List<AssembleDO> selectByAssembleId(String assembleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_info
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(AssembleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_info
     *
     * @mbg.generated Tue Apr 30 15:58:31 GMT+08:00 2019
     */
    int updateByPrimaryKey(AssembleDO record);
}