package com.collagehelper.dao;

import com.collagehelper.dataobject.CartDO;

import java.util.List;

public interface CartDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    int insert(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    int insertSelective(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    CartDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated Tue Apr 23 11:50:26 GMT+08:00 2019
     */
    int updateByPrimaryKey(CartDO record);

    List<CartDO> selectByPhone(String phone);
}