package com.collagehelper.dao;

import com.collagehelper.dataobject.CGDO;

import java.util.List;

public interface CGDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_goods
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_goods
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    int insert(CGDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_goods
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    int insertSelective(CGDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_goods
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    CGDO selectByPrimaryKey(Integer id);

    List<CGDO> selectByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_goods
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CGDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_goods
     *
     * @mbg.generated Thu May 02 20:20:11 GMT+08:00 2019
     */
    int updateByPrimaryKey(CGDO record);
}