package com.collagehelper.dao;

import com.collagehelper.dataobject.ChatDO;

import java.util.List;

public interface ChatDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Fri May 03 16:56:19 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Fri May 03 16:56:19 GMT+08:00 2019
     */
    int insert(ChatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Fri May 03 16:56:19 GMT+08:00 2019
     */
    int insertSelective(ChatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Fri May 03 16:56:19 GMT+08:00 2019
     */
    ChatDO selectByPrimaryKey(Integer id);

    List<ChatDO> selectByCPAndSP(String customerPhone,String sellerPhone);

    List<ChatDO> selectByCPhone(String customerPhone);

    List<ChatDO> selectBySPhone(String sellerPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Fri May 03 16:56:19 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ChatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Fri May 03 16:56:19 GMT+08:00 2019
     */
    int updateByPrimaryKey(ChatDO record);
}