package com.collagehelper.dao;

import com.collagehelper.dataobject.CTSDO;

import java.util.List;

public interface CTSDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_to_seller
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_to_seller
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int insert(CTSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_to_seller
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int insertSelective(CTSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_to_seller
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    CTSDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_to_seller
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CTSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_to_seller
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int updateByPrimaryKey(CTSDO record);

    List<CTSDO> getSellerByCPhone(String cPhone);
}