package com.collagehelper.dao;

import com.collagehelper.dataobject.FormDO;
import com.collagehelper.dataobject.FormSDO;

import java.util.List;

public interface FormSDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info_seller
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info_seller
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int insert(FormSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info_seller
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int insertSelective(FormSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info_seller
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    FormSDO selectByPrimaryKey(Integer id);

    List<FormSDO> selectByCustomerPhone(String customerPhone);

    List<FormSDO> selectBySellerPhone(String sellerPhone);

    List<FormSDO> selectByStatus(String status);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info_seller
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(FormSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info_seller
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int updateByPrimaryKey(FormSDO record);

    int updateByOrderId(String orderId,String status);
}