package com.collagehelper.dao;

import com.collagehelper.dataobject.FormDO;

import java.util.List;

public interface FormDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int insert(FormDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int insertSelective(FormDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    FormDO selectByPrimaryKey(Integer id);

    List<FormDO> selectByCustomerPhone(String customerPhone);

    List<FormDO> selectBySellerPhone(String sellerPhone);

    List<FormDO> selectByStatus(String status,String customerPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(FormDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_info
     *
     * @mbg.generated Fri May 10 14:20:13 GMT+08:00 2019
     */
    int updateByPrimaryKey(FormDO record);

    int updateByOrderId(String orderId,String status);
}