package com.collagehelper.dao;

import com.collagehelper.dataobject.GoodsDO;

import java.util.List;

public interface GoodsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int insert(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int insertSelective(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    GoodsDO selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated Sat Apr 20 14:25:17 GMT+08:00 2019
     */
    int updateByPrimaryKey(GoodsDO record);

    List<GoodsDO> selectByPhone(String phone);

    List<GoodsDO> getGoodsByName(String name);
}