package com.collagehelper.dao;

import com.collagehelper.dataobject.OrderSDO;

import java.util.List;

public interface OrderSDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_seller
     *
     * @mbg.generated Thu Apr 25 15:00:03 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_seller
     *
     * @mbg.generated Thu Apr 25 15:00:03 GMT+08:00 2019
     */
    int insert(OrderSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_seller
     *
     * @mbg.generated Thu Apr 25 15:00:03 GMT+08:00 2019
     */
    int insertSelective(OrderSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_seller
     *
     * @mbg.generated Thu Apr 25 15:00:03 GMT+08:00 2019
     */
    OrderSDO selectByPrimaryKey(Integer id);

    List<OrderSDO> selectByCustomerPhone(String customerPhone);

    List<OrderSDO> selectBySellerPhone(String sellerPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_seller
     *
     * @mbg.generated Thu Apr 25 15:00:03 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(OrderSDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info_seller
     *
     * @mbg.generated Thu Apr 25 15:00:03 GMT+08:00 2019
     */
    int updateByPrimaryKey(OrderSDO record);
}